# Generated by Django 4.2.20 on 2025-05-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_created_at_order_ordered_at_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
